services:
  nginx:
    ports:
      - "${DEV_PORT_PHP}:80"

  php-fpm:
    environment:
      - APP_ENV=local
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "${APP_URL}:host-gateway"
      - "${WS_URL}:host-gateway"

  php-horizon:
    environment:
      - APP_ENV=local
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "${APP_URL}:host-gateway"
      - "${WS_URL}:host-gateway"

  node:
    environment:
      - NODE_ENV=development
    command: "tail -f /dev/null"
    ports:
      - "${PORT_NODE}:5173"
    extra_hosts:
      - "${WS_URL}:host-gateway"
    volumes:
      - ./src:/var/www

  db-mysql:
    ports:
      - "${DEV_PORT_DB}:3306"
    build:
      context: ./config/mysql-dev
      args:
        - MYSQL_DATABASE_TESTING=${DB_DATABASE_TESTING}
        - MYSQL_USERNAME_TESTING=${DB_USERNAME_TESTING}
        - MYSQL_PASSWORD_TESTING=${DB_PASSWORD_TESTING}
